// apps/desktop/src/mainview/App.vue
<template>
  <DesignBoard v-if="isDesign" />
  <div v-else class="flex h-full flex-col bg-background">
    <MurmurHeader />

    <ScrollAreaRoot class="min-h-0 flex-1 overflow-hidden">
      <ScrollAreaViewport class="h-full w-full">
        <main class="px-4 pb-4 pt-1">
          <MonitorView v-if="view === 'live'" />
          <UsageView v-else-if="view === 'usage'" />
          <SetupView v-else-if="view === 'setup'" />
          <SettingsView v-else />
        </main>
      </ScrollAreaViewport>
      <ScrollBar orientation="vertical" class="w-1.5 p-px">
        <ScrollAreaThumb class="rounded-full bg-foreground/15" />
      </ScrollBar>
    </ScrollAreaRoot>

    <footer class="flex items-center border-t border-hairline bg-card px-3 py-2">
      <nav class="flex items-center gap-0.5 rounded-full bg-muted p-0.5" aria-label="主视图">
        <button
          v-for="item in navItems"
          :key="item.id"
          type="button"
          class="flex items-center gap-1.5 rounded-full px-3 py-1 text-[11px] font-medium transition-colors duration-fast"
          :class="view === item.id ? 'bg-card text-foreground shadow-raised' : 'text-muted-foreground hover:text-foreground'"
          @click="view = item.id"
        >
          <component :is="item.icon" :size="12" :stroke-width="1.8" />
          {{ item.label }}
          <span v-if="item.id === 'live' && store.waitingCount" class="font-mono text-[9.5px] tabular-nums text-waiting">{{ store.waitingCount }}</span>
        </button>
      </nav>
      <div class="ml-auto flex items-center gap-1">
        <button
          type="button"
          class="flex h-7 w-7 items-center justify-center rounded-md text-faint transition-colors duration-fast hover:bg-stale/10 hover:text-stale"
          title="退出 Murmur"
          @click="store.quit()"
        >
          <Power :size="13" />
        </button>
      </div>
    </footer>
  </div>
</template>

<script setup lang="ts">
import { onMounted, ref } from "vue";
import { Activity, BarChart3, Power, Settings, Settings2 } from "lucide-vue-next";
import {
  ScrollAreaRoot,
  ScrollAreaScrollbar as ScrollBar,
  ScrollAreaThumb,
  ScrollAreaViewport,
} from "reka-ui";

import DesignBoard from "@/design/design-board.vue";
import MonitorView from "@/components/monitor-view.vue";
import MurmurHeader from "@/components/murmur-header.vue";
import SettingsView from "@/components/settings-view.vue";
import SetupView from "@/components/setup-view.vue";
import UsageView from "@/components/usage-view.vue";
import { useMurmurStore } from "@/store/murmur";

const store = useMurmurStore();
const isDesign = ref(location.hash.startsWith("#/design"));
const view = ref<"live" | "usage" | "setup" | "settings">("live");
const navItems = [
  { id: "live" as const, label: "动态", icon: Activity },
  { id: "usage" as const, label: "用量", icon: BarChart3 },
  { id: "setup" as const, label: "工具", icon: Settings2 },
  { id: "settings" as const, label: "设置", icon: Settings },
];

onMounted(() => store.refresh());
</script>

// apps/desktop/src/mainview/app.tsx
/**
 * React 面板外壳：玻璃 overlay 布局——刊头/底栏 absolute 浮于滚动区之上
 * （glass-chrome 毛玻璃，内容从其下穿过），底栏为编号式导航。
 * `#/design` hash 进设计板预览组件。
 */

import { Activity, BarChart3, Power, Settings, Settings2 } from "lucide-react";
import { useEffect, useState } from "react";

import MonitorView from "@/components/monitor-view";
import MurmurHeader from "@/components/murmur-header";
import SessionsView from "@/components/sessions-view";
import SettingsView from "@/components/settings-view";
import SetupView from "@/components/setup-view";
import UsageView from "@/components/usage-view";
import { ScrollArea } from "@/components/ui/scroll-area";
import DesignBoard from "@/design/design-board";
import { applyAppearance } from "@/lib/appearance";
import { waitingCount } from "@/lib/selectors";
import { cn } from "@/lib/utils";
import { useMurmurStore } from "@/store/murmur";

import type { ComponentType } from "react";

type ViewId = "live" | "usage" | "setup" | "settings";

const NAV_ITEMS: { id: ViewId; label: string; icon: ComponentType<{ size?: number; strokeWidth?: number }> }[] = [
  { id: "live", label: "动态", icon: Activity },
  { id: "usage", label: "用量", icon: BarChart3 },
  { id: "setup", label: "工具", icon: Settings2 },
  { id: "settings", label: "设置", icon: Settings },
];

export default function App() {
  const isDesign = location.hash.startsWith("#/design");
  // 独立窗口内容：会话文件管理页（views://…#/files 由第二 BrowserWindow 加载）。
  const isSessions = location.hash.startsWith("#/files");
  const [view, setView] = useState<ViewId>("live");

  const snapshot = useMurmurStore((s) => s.snapshot);
  const refresh = useMurmurStore((s) => s.refresh);
  const quit = useMurmurStore((s) => s.quit);
  const loadSettings = useMurmurStore((s) => s.loadSettings);
  const theme = useMurmurStore((s) => s.settingsSnap?.settings.theme ?? "system");
  const font = useMurmurStore((s) => s.settingsSnap?.settings.font ?? "");
  const waiting = waitingCount(snapshot);

  useEffect(() => {
    void refresh();
    void loadSettings();
  }, [refresh, loadSettings]);

  /* 外观在首帧应用：settings 未到时按 system 渲染，到达后纠正——面板隐藏加载，
     全程不可见。effect 必须早于 #/design 早退，设计板同样吃主题。 */
  useEffect(() => applyAppearance(theme, font), [theme, font]);

  if (isDesign) return <DesignBoard />;
  if (isSessions) return <SessionsView />;

  return (
    <div className="relative h-full bg-background">
      {/* 滚动区铺满，上下留白让位于玻璃 chrome（--chrome-top/--chrome-bottom） */}
      <ScrollArea className="h-full overflow-hidden">
        <main
          key={view}
          className="px-4 pb-4"
          style={{
            paddingTop: "calc(var(--chrome-top) + 8px)",
            paddingBottom: "calc(var(--chrome-bottom) + 12px)",
          }}
        >
          {view === "live" && <MonitorView />}
          {view === "usage" && <UsageView />}
          {view === "setup" && <SetupView />}
          {view === "settings" && <SettingsView />}
        </main>
      </ScrollArea>

      {/* 玻璃刊头：滚动内容从其下穿过；hairline 分隔在无滚动时读作普通分区线 */}
      <div className="glass-chrome absolute inset-x-0 top-0 z-20 border-b border-hairline/50">
        <MurmurHeader />
      </div>

      <footer className="glass-chrome absolute inset-x-0 bottom-0 z-20 border-t border-hairline/50 px-3 py-2">
        <div className="flex items-center">
          <nav className="flex items-center gap-0.5 rounded-full bg-muted p-0.5" aria-label="主视图">
            {NAV_ITEMS.map((item) => {
              const Icon = item.icon;
              const active = view === item.id;
              return (
                <button
                  key={item.id}
                  type="button"
                  className={cn(
                    "flex items-center gap-1.5 rounded-full border px-3 py-1 text-meta font-medium transition-colors duration-fast",
                    active
                      ? "border-hairline bg-raised text-foreground"
                      : "border-transparent text-muted-foreground hover:text-foreground",
                  )}
                  onClick={() => setView(item.id)}
                >
                  <Icon size={12} strokeWidth={1.8} />
                  {item.label}
                  {item.id === "live" && waiting > 0 && (
                    <span className="font-mono text-micro tabular-nums text-waiting">{waiting}</span>
                  )}
                </button>
              );
            })}
          </nav>
          <button
            type="button"
            className="ml-auto flex h-7 w-7 items-center justify-center rounded-md text-faint transition-colors duration-fast hover:bg-stale/10 hover:text-stale"
            title="退出 Murmur"
            onClick={quit}
          >
            <Power size={13} />
          </button>
        </div>
      </footer>
    </div>
  );
}
