// apps/desktop/src/mainview/components/monitor-view.tsx
/** 动态视图：尺规索引条（计数 + 新鲜度）→ waiting 琥珀头条 → 编号分组列表 → 已停更清单。
 *  版块入场 stagger（enter + 序位 delay）；空态投放椋鸟群签名时刻。 */

import { useMemo } from "react";

import AgentIcon from "@/components/agent-icon";
import AgentRow from "@/components/agent-row";
import AnimatedNumber from "@/components/animated-number";
import Murmuration from "@/components/murmuration";
import StatusDot from "@/components/status-dot";
import { AGENT_META } from "@/lib/agent-meta";
import { fmtTokens } from "@/lib/format";
import { allSessions, todayTokens } from "@/lib/selectors";
import { cn } from "@/lib/utils";
import { useMurmurStore } from "@/store/murmur";

import type { AgentId, WaitingReason } from "@core/types";

export default function MonitorView() {
  const snapshot = useMurmurStore((s) => s.snapshot);
  const loading = useMurmurStore((s) => s.loading);

  const sessions = useMemo(() => allSessions(snapshot), [snapshot]);
  const waitingSessions = sessions.filter((s) => s.status === "waiting");
  const workingSessions = sessions.filter((s) => s.status === "working");
  const staleSessions = sessions.filter((s) => s.status === "stale");
  const activeSessions = sessions.filter((s) => ["waiting", "working"].includes(s.status));
  const activeAgents = (snapshot?.agents ?? []).filter((a) =>
    a.sessions.some((s) => ["waiting", "working"].includes(s.status)),
  );
  const tokens = todayTokens(snapshot);
  const freshness = snapshot ? `更新于 ${age(snapshot.generatedAt)}` : "连接中";

  /* 入场序位：渲染顺序即 stagger 顺序，每次渲染从 0 重新排 */
  let slot = 0;
  const enterDelay = () => `${slot++ * 40}ms`;

  if (loading) {
    return (
      <div className="space-y-3" aria-live="polite">
        <div className="h-20 animate-pulse rounded-item bg-raised" />
        <div className="h-14 animate-pulse rounded-item bg-raised" />
        <div className="h-14 animate-pulse rounded-item bg-raised" />
      </div>
    );
  }

  return (
    <div className="flex flex-col gap-4">
      {/* 索引条：计数 + 新鲜度；上边线由玻璃刊头的底边线兼任，只保留下规线 */}
      <section
        className="animate-enter flex items-center justify-between border-b border-hairline py-2"
        style={{ animationDelay: enterDelay() }}
      >
        <div className="flex items-center gap-3.5 text-meta text-muted-foreground">
          <span>
            运行中
            <AnimatedNumber
              value={workingSessions.length}
              className={cn(
                "ml-1 font-mono text-detail",
                workingSessions.length ? "font-medium text-working" : "text-faint",
              )}
            />
          </span>
          <span>
            需处理
            <AnimatedNumber
              value={waitingSessions.length}
              className={cn(
                "ml-1 font-mono text-detail",
                waitingSessions.length ? "font-medium text-waiting" : "text-faint",
              )}
            />
          </span>
          <span>
            今日令牌
            <AnimatedNumber
              value={tokens ? fmtTokens(tokens) : "·"}
              className={cn("ml-1 font-mono text-detail", tokens ? "font-medium text-foreground" : "text-faint")}
            />
          </span>
        </div>
        <span className="font-mono text-micro tabular-nums text-faint">{freshness}</span>
      </section>

      {/* 头条：waiting 的第一条会话——琥珀左边条 + 慢呼吸光晕 + 淡染卡面，本页唯一 hero */}
      {waitingSessions.length > 0 && (
        <section
          className="animate-enter relative overflow-hidden rounded-item border border-waiting/25 bg-waiting/[0.06] shadow-raised"
          style={{ animationDelay: enterDelay() }}
          aria-live="polite"
        >
          <span className="animate-hero-breathe pointer-events-none absolute -left-8 -top-10 h-24 w-44 rounded-full bg-waiting/15 blur-2xl" />
          <span className="absolute inset-y-0 left-0 w-[3px] bg-waiting" />
          <div className="px-4 py-3.5">
            <p className="text-micro font-semibold tracking-[0.1em] text-waiting">
              轮到你了 · {agentName(waitingSessions[0].agent)}
            </p>
            <p className="mt-1.5 text-title font-medium leading-snug">
              {waitingSessions[0].title || "一个任务正在等你继续"}
            </p>
            <p className="mt-1 text-meta text-muted-foreground">
              {waitingReason(waitingSessions[0].waitingReason)} · {age(waitingSessions[0].lastEventAt)}
            </p>
          </div>
          {waitingSessions.length > 1 && (
            <div className="border-t border-waiting/15 px-4 py-2 text-meta text-muted-foreground">
              还有 {waitingSessions.length - 1} 个任务等待处理
            </div>
          )}
        </section>
      )}

      {activeAgents.length > 0 && (
        <section className="animate-enter space-y-2" style={{ animationDelay: enterDelay() }}>
          <div className="flex items-center gap-2 px-0.5">
            <span className="eyebrow flex items-baseline gap-1.5 text-faint">
              <span className="font-mono">01</span>正在发生
            </span>
            <span className="h-px flex-1 bg-hairline" />
            <span className="font-mono text-micro tabular-nums text-faint">{activeSessions.length}</span>
          </div>
          {/* 分组列表：单一面 + hairline 分隔，AgentRow 自身不带卡片壳 */}
          <div className="divide-y divide-hairline/60 overflow-hidden rounded-item border border-hairline bg-card shadow-raised">
            {activeAgents.map((agent) => (
              <AgentRow key={agent.agent} agent={agent} />
            ))}
          </div>
        </section>
      )}

      {staleSessions.length > 0 && (
        <section className="animate-enter space-y-2" style={{ animationDelay: enterDelay() }}>
          <div className="flex items-center gap-2 px-0.5">
            <span className="eyebrow flex items-baseline gap-1.5 text-stale">
              <span className="font-mono">02</span>已停止更新
            </span>
            <span className="h-px flex-1 bg-stale/20" />
          </div>
          <div className="divide-y divide-hairline/60 overflow-hidden rounded-item border border-hairline bg-card shadow-raised">
            {staleSessions.map((session) => (
              <div key={session.sessionId} className="flex items-center gap-3 bg-stale/[0.03] px-3.5 py-2.5">
                <AgentIcon agent={session.agent} size={26} />
                <div className="min-w-0 flex-1">
                  <div className="flex items-center gap-2">
                    <span className="truncate text-detail font-medium">{session.title || "未命名任务"}</span>
                    <StatusDot status={session.status} size={7} />
                  </div>
                  <p className="mt-0.5 truncate text-meta text-muted-foreground">
                    {agentName(session.agent)} · {age(session.lastEventAt)}没有更新
                  </p>
                </div>
              </div>
            ))}
          </div>
        </section>
      )}

      {/* 空态：椋鸟群在栖枝上休憩——签名时刻，群鸟游动 + 峰点琥珀 */}
      {!activeSessions.length && !staleSessions.length && (
        <div className="animate-enter px-4 py-14 text-center" style={{ animationDelay: enterDelay() }}>
          <Murmuration size={120} className="mx-auto" />
          <p className="mt-4 text-body font-medium">现在很安静</p>
          <p className="mt-1.5 text-meta text-muted-foreground">启动一个工具后，Murmur 会在这里显示它的任务。</p>
        </div>
      )}
    </div>
  );
}

function agentName(agent: AgentId) {
  return AGENT_META[agent].name;
}

function waitingReason(reason?: WaitingReason) {
  if (reason === "approval") return "等待批准";
  if (reason === "question") return "等待回答";
  return "本轮完成，等待继续";
}

function age(at: number) {
  const seconds = Math.max(0, Math.floor((Date.now() - at) / 1000));
  if (seconds < 10) return "刚刚";
  if (seconds < 60) return `${seconds}秒前`;
  const minutes = Math.floor(seconds / 60);
  if (minutes < 60) return `${minutes}分钟前`;
  return `${Math.floor(minutes / 60)}小时前`;
}

// apps/desktop/src/mainview/components/monitor-view.vue
<template>
  <div class="flex flex-col gap-4">
    <div v-if="store.loading" class="space-y-3" aria-live="polite">
      <div class="h-20 animate-pulse rounded-item bg-card shadow-raised" />
      <div class="h-14 animate-pulse rounded-item bg-card shadow-raised" />
      <div class="h-14 animate-pulse rounded-item bg-card shadow-raised" />
    </div>

    <template v-else>
      <!-- 尺规索引条：计数 + 新鲜度，上下 hairline 夹出版面节奏 -->
      <section class="flex items-center justify-between border-y border-hairline py-2">
        <div class="flex items-center gap-3.5 text-[10.5px] text-muted-foreground">
          <span>
            运行中
            <span class="ml-1 font-mono tabular-nums" :class="workingSessions.length ? 'font-medium text-working' : 'text-faint'">{{ workingSessions.length }}</span>
          </span>
          <span>
            需处理
            <span class="ml-1 font-mono tabular-nums" :class="waitingSessions.length ? 'font-medium text-waiting' : 'text-faint'">{{ waitingSessions.length }}</span>
          </span>
          <span>
            今日令牌
            <span class="ml-1 font-mono tabular-nums" :class="store.todayTokens ? 'font-medium text-foreground' : 'text-faint'">{{ store.todayTokens ? fmt(store.todayTokens) : '·' }}</span>
          </span>
        </div>
        <span class="font-mono text-[9.5px] tabular-nums text-faint">{{ freshness }}</span>
      </section>

      <!-- 头条：waiting 的第一条会话，琥珀左边条 + 衬线标题 -->
      <section
        v-if="waitingSessions.length"
        class="relative overflow-hidden rounded-item border border-hairline bg-card shadow-raised"
        aria-live="polite"
      >
        <span class="absolute inset-y-0 left-0 w-[2.5px] bg-waiting" />
        <div class="px-3.5 py-3">
          <p class="text-[9.5px] font-semibold uppercase tracking-[0.14em] text-waiting">
            轮到你了 · {{ agentName(waitingSessions[0].agent) }}
          </p>
          <p class="mt-1.5 font-display text-[14.5px] font-medium leading-snug">
            {{ waitingSessions[0].title || '一个任务正在等你继续' }}
          </p>
          <p class="mt-1 text-[10.5px] text-muted-foreground">
            {{ waitingReason(waitingSessions[0].waitingReason) }} · {{ age(waitingSessions[0].lastEventAt) }}
          </p>
        </div>
        <div v-if="waitingSessions.length > 1" class="border-t border-hairline px-3.5 py-2 text-[10.5px] text-muted-foreground">
          还有 {{ waitingSessions.length - 1 }} 个任务等待处理
        </div>
      </section>

      <section v-if="activeAgents.length" class="space-y-2">
        <div class="flex items-center gap-2 px-0.5">
          <span class="text-[10px] font-semibold tracking-[0.12em] text-faint">正在发生</span>
          <span class="h-px flex-1 bg-hairline" />
          <span class="font-mono text-[10px] tabular-nums text-faint">{{ activeSessions.length }}</span>
        </div>
        <AgentRow v-for="agent in activeAgents" :key="agent.agent" :agent="agent" />
      </section>

      <section v-if="staleSessions.length" class="space-y-2">
        <div class="flex items-center gap-2 px-0.5">
          <span class="text-[10px] font-semibold uppercase tracking-[0.16em] text-stale">已停止更新</span>
          <span class="h-px flex-1 bg-stale/20" />
        </div>
        <div v-for="session in staleSessions" :key="session.sessionId" class="flex items-center gap-3 rounded-item border border-stale/25 bg-stale/8 px-3 py-2.5">
          <AgentIcon :agent="session.agent" :size="26" />
          <div class="min-w-0 flex-1">
            <div class="flex items-center gap-2">
              <span class="truncate text-[12px] font-medium">{{ session.title || '未命名任务' }}</span>
              <StatusDot :status="session.status" :size="7" />
            </div>
            <p class="mt-0.5 truncate text-[10.5px] text-muted-foreground">{{ agentName(session.agent) }} · {{ age(session.lastEventAt) }}没有更新</p>
          </div>
        </div>
      </section>

      <div v-if="!activeSessions.length && !staleSessions.length" class="rounded-item border border-hairline bg-card px-4 py-10 text-center shadow-raised">
        <MurmurMark :size="30" class="mx-auto text-faint" />
        <p class="mt-3.5 font-display text-[16px] italic">现在很安静</p>
        <p class="mt-1.5 text-[11px] text-muted-foreground">启动一个工具后，Murmur 会在这里显示它的任务。</p>
      </div>
    </template>
  </div>
</template>

<script setup lang="ts">
import { computed } from "vue";

import AgentIcon from "@/components/agent-icon.vue";
import AgentRow from "@/components/agent-row.vue";
import MurmurMark from "@/components/murmur-mark.vue";
import StatusDot from "@/components/status-dot.vue";
import { AGENT_META } from "@/lib/agent-meta";
import { useMurmurStore } from "@/store/murmur";

import type { AgentId, WaitingReason } from "@core/types";

const store = useMurmurStore();
const sessions = computed(() => store.allSessions);
const waitingSessions = computed(() => sessions.value.filter((s) => s.status === "waiting"));
const workingSessions = computed(() => sessions.value.filter((s) => s.status === "working"));
const staleSessions = computed(() => sessions.value.filter((s) => s.status === "stale"));
const activeSessions = computed(() => sessions.value.filter((s) => ["waiting", "working"].includes(s.status)));
const activeAgents = computed(() =>
  (store.snapshot?.agents ?? []).filter((a) => a.sessions.some((s) => ["waiting", "working"].includes(s.status))),
);
const freshness = computed(() => store.snapshot ? `更新于 ${age(store.snapshot.generatedAt)}` : "连接中");

function agentName(agent: AgentId) {
  return AGENT_META[agent].name;
}

function waitingReason(reason?: WaitingReason) {
  if (reason === "approval") return "等待批准";
  if (reason === "question") return "等待回答";
  return "本轮完成，等待继续";
}

function age(at: number) {
  const seconds = Math.max(0, Math.floor((Date.now() - at) / 1000));
  if (seconds < 10) return "刚刚";
  if (seconds < 60) return `${seconds}秒前`;
  const minutes = Math.floor(seconds / 60);
  if (minutes < 60) return `${minutes}分钟前`;
  return `${Math.floor(minutes / 60)}小时前`;
}

function fmt(n: number) {
  if (n >= 1_000_000_000) return `${(n / 1_000_000_000).toFixed(1)}G`;
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`;
  if (n >= 1_000) return `${(n / 1_000).toFixed(1)}k`;
  return String(n);
}
</script>
