// apps/desktop/src/mainview/components/murmur-header.vue
<template>
  <!-- 刊头：衬线字标 + folio 微信息行（日期 · 运行中计数）+ 待处理徽标，下方横贯栖枝签名。 -->
  <header class="px-4 pb-3 pt-4">
    <div class="flex items-start justify-between gap-3">
      <div class="flex items-center gap-2.5">
        <span class="mark-shell flex h-8 w-8 items-center justify-center rounded-lg text-card">
          <MurmurMark :size="20" />
        </span>
        <div>
          <p class="font-display text-[19px] font-semibold italic leading-none tracking-[-0.01em]">Murmur</p>
          <p class="mt-1.5 text-[10px] text-muted-foreground">{{ folio }}</p>
        </div>
      </div>
      <div class="flex shrink-0 items-center gap-1.5 pt-0.5">
        <span
          v-if="store.waitingCount"
          class="flex items-center gap-1.5 rounded-full border border-waiting/30 bg-waiting/10 px-2 py-0.5 text-[10px] font-semibold text-waiting"
        >
          <span class="h-1.5 w-1.5 animate-attention rounded-full bg-waiting" />
          {{ store.waitingCount }} 待处理
        </span>
        <button
          type="button"
          class="flex h-6 w-6 items-center justify-center rounded-md text-faint transition-colors duration-fast hover:bg-muted hover:text-foreground"
          title="刷新额度"
          :disabled="refreshing"
          @click="refreshQuotas"
        >
          <RefreshCw :size="12" :class="{ 'animate-spin': refreshing }" />
        </button>
      </div>
    </div>
    <PerchStrip class="mt-3" />
  </header>
</template>

<script setup lang="ts">
import { computed, ref } from "vue";
import { RefreshCw } from "lucide-vue-next";

import MurmurMark from "@/components/murmur-mark.vue";
import PerchStrip from "@/components/perch-strip.vue";
import { useMurmurStore } from "@/store/murmur";

const store = useMurmurStore();
const refreshing = ref(false);

const WEEKDAYS = ["周日", "周一", "周二", "周三", "周四", "周五", "周六"];

/* 面板失焦即关，folio 取挂载时刻即可，不做时钟轮询。 */
const folio = computed(() => {
  const d = new Date();
  const parts = [`${WEEKDAYS[d.getDay()]} ${d.getMonth() + 1}月${d.getDate()}日`];
  parts.push(store.workingCount ? `${store.workingCount} 运行中` : "安静");
  return parts.join(" · ");
});

async function refreshQuotas() {
  if (refreshing.value) return;
  refreshing.value = true;
  try {
    await store.refreshQuotas();
  } finally {
    setTimeout(() => (refreshing.value = false), 400);
  }
}
</script>

// apps/desktop/src/mainview/components/murmur-header.tsx
/** 刊头：裸放 murmur-mark + MURMUR 眉题 + 状态头条（面板开口说的第一句话）
 *  + folio 微信息行（日期 · 已接入数），下方横贯栖枝签名。
 *  绝对定位浮于滚动区之上（glass-chrome），高度计入 --chrome-top。 */

import { RefreshCw } from "lucide-react";
import { useMemo, useState } from "react";

import AnimatedNumber from "@/components/animated-number";
import MurmurMark from "@/components/murmur-mark";
import PerchStrip from "@/components/perch-strip";
import { waitingCount, workingCount } from "@/lib/selectors";
import { useMurmurStore } from "@/store/murmur";

const WEEKDAYS = ["周日", "周一", "周二", "周三", "周四", "周五", "周六"];

export default function MurmurHeader() {
  const snapshot = useMurmurStore((s) => s.snapshot);
  const refreshQuotas = useMurmurStore((s) => s.refreshQuotas);
  const [refreshing, setRefreshing] = useState(false);

  const waiting = useMemo(() => waitingCount(snapshot), [snapshot]);
  const working = useMemo(() => workingCount(snapshot), [snapshot]);

  const agents = snapshot?.agents ?? [];
  const connected = agents.filter((a) => a.install.installed && !a.disabled).length;

  /* 面板失焦即关，日期取挂载时刻即可（不随时间刷新），计数跟随快照。 */
  const folio = useMemo(() => {
    const d = new Date();
    return `${WEEKDAYS[d.getDay()]} ${d.getMonth() + 1}月${d.getDate()}日 · 已接入 ${connected}/${agents.length || 5}`;
  }, [connected, agents.length]);

  async function onRefresh() {
    if (refreshing) return;
    setRefreshing(true);
    try {
      await refreshQuotas();
    } finally {
      setTimeout(() => setRefreshing(false), 400);
    }
  }

  return (
    <header className="px-4 pb-2.5 pt-3.5">
      <div className="flex items-center justify-between gap-3">
        <div className="flex items-center gap-2">
          <MurmurMark size={20} live={waiting > 0} className="text-foreground" />
          <span className="font-mono text-micro font-medium tracking-[0.18em] text-muted-foreground">MURMUR</span>
        </div>
        <button
          type="button"
          className="flex h-6 w-6 items-center justify-center rounded-md text-faint transition-colors duration-fast hover:bg-muted hover:text-foreground"
          title="刷新额度"
          disabled={refreshing}
          onClick={onRefresh}
        >
          <RefreshCw size={12} className={refreshing ? "animate-spin" : undefined} />
        </button>
      </div>

      {/* 状态头条：面板的第一句话，title 档当家；waiting 时数字琥珀 */}
      <p className="mt-2 text-title font-semibold">
        {waiting > 0 ? (
          <>
            <AnimatedNumber value={waiting} className="font-mono text-waiting" />
            <span className="ml-1">个任务轮到你了</span>
          </>
        ) : working > 0 ? (
          <>
            <AnimatedNumber value={working} className="font-mono" />
            <span className="ml-1">个工具正在干活</span>
          </>
        ) : (
          "现在很安静"
        )}
      </p>
      <p className="mt-0.5 text-meta text-muted-foreground">{folio}</p>

      <PerchStrip className="mt-2.5" />
    </header>
  );
}
