// apps/desktop/src/mainview/components/usage-view.vue
<template>
  <div class="flex flex-col gap-3">
    <template v-if="hasData">
      <!-- ── 近 10 周热力图（周为列，日为行，GitHub 式；色阶 ink→琥珀）── -->
      <section class="rounded-item border border-hairline bg-card px-3 py-2.5 shadow-raised">
        <div class="mb-2 flex items-baseline justify-between">
          <span class="flex items-baseline gap-1.5">
            <span class="font-mono text-[9.5px] text-faint">01</span>
            <span class="text-[11px] font-semibold">近 10 周</span>
          </span>
          <span class="font-mono text-[10px] tabular-nums text-faint">{{ fmt(totalTokens) }} 令牌</span>
        </div>
        <div ref="heatBox" class="relative">
          <div class="flex gap-[3px]">
            <div v-for="(week, wi) in heatWeeks" :key="wi" class="flex flex-1 flex-col gap-[3px]">
              <span
                v-for="cell in week"
                :key="cell.day"
                class="h-[11px] w-full rounded-[2.5px] transition-shadow duration-fast hover:ring-1 hover:ring-foreground/25"
                :style="{ background: cell.color }"
                @mouseenter="onHeatEnter($event, cell)"
                @mouseleave="heatTip = null"
              />
            </div>
          </div>
          <ChartTip :tip="heatTip">
            <p v-if="heatCell" class="whitespace-nowrap text-[10.5px]">
              <span class="font-mono tabular-nums text-faint">{{ heatCell.day }}</span>
              <span class="mx-1.5 text-faint">·</span>
              <span class="font-mono tabular-nums font-medium">{{ fmt(heatCell.tokens) }} 令牌</span>
            </p>
          </ChartTip>
        </div>
      </section>

      <!-- ── 近 7 天堆积柱（按 agent 分色）── -->
      <section class="rounded-item border border-hairline bg-card px-3 py-2.5 shadow-raised">
        <div class="mb-2 flex items-baseline justify-between">
          <span class="flex items-baseline gap-1.5">
            <span class="font-mono text-[9.5px] text-faint">02</span>
            <span class="text-[11px] font-semibold">近 7 天 · 按工具</span>
          </span>
          <span class="font-mono text-[10px] tabular-nums text-faint">{{ fmt(weekTokens) }} 令牌</span>
        </div>
        <div ref="barBox" class="relative">
          <div class="flex h-[84px] items-end gap-2">
            <div v-for="d in last7" :key="d.day" class="flex flex-1 flex-col items-center gap-1">
              <div class="flex w-full flex-col-reverse gap-px" :style="{ height: '64px' }">
                <div
                  v-for="seg in d.segments"
                  :key="seg.agent"
                  class="w-full rounded-[2px] transition-opacity duration-fast hover:opacity-80"
                  :style="{ height: seg.h + 'px', background: agentColor(seg.agent) }"
                  @mouseenter="onBarEnter($event, seg)"
                  @mouseleave="barTip = null"
                />
              </div>
              <span class="font-mono text-[9px] tabular-nums text-faint">{{ d.label }}</span>
            </div>
          </div>
          <ChartTip :tip="barTip">
            <p v-if="barSeg" class="whitespace-nowrap text-[10.5px]">
              <span class="font-medium">{{ segName(barSeg.agent) }}</span>
              <span class="mx-1.5 text-faint">·</span>
              <span class="font-mono tabular-nums">{{ fmt(barSeg.tokens) }} 令牌</span>
            </p>
          </ChartTip>
        </div>
      </section>

      <!-- ── 近 7 天模型折线（准星 + 悬浮明细）── -->
      <section class="rounded-item border border-hairline bg-card px-3 py-2.5 shadow-raised">
        <div class="mb-2 flex items-baseline gap-1.5">
          <span class="font-mono text-[9.5px] text-faint">03</span>
          <span class="text-[11px] font-semibold">近 7 天 · 按模型</span>
        </div>
        <ModelLineChart :days="lineDays" :series="lineSeries" />
        <div class="mt-1.5 flex flex-wrap gap-x-3 gap-y-1">
          <span v-for="m in lineSeries" :key="m.name" class="flex items-center gap-1 text-[9.5px] text-muted-foreground">
            <span class="inline-block h-[6px] w-[6px] rounded-full" :style="{ background: m.color }" />
            {{ m.name }}
            <span class="font-mono tabular-nums text-faint">{{ fmt(m.total) }}</span>
          </span>
        </div>
      </section>
    </template>

    <div v-else class="rounded-item border border-hairline bg-card px-3 py-10 text-center shadow-raised">
      <MurmurMark :size="26" class="mx-auto text-faint" />
      <p class="mt-3 font-display text-[15px] italic">还没有用量记录</p>
      <p class="mt-1.5 text-[11.5px] leading-relaxed text-muted-foreground">
        agent 跑起来后，这里会出现热力图与模型用量曲线
      </p>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from "vue";

import ChartTip from "@/components/chart-tip.vue";
import ModelLineChart from "@/components/model-line-chart.vue";
import MurmurMark from "@/components/murmur-mark.vue";
import { AGENT_META } from "@/lib/agent-meta";
import { anchorTop } from "@/lib/chart-tip";
import { useMurmurStore } from "@/store/murmur";

import type { ChartTipState } from "@/lib/chart-tip";
import type { UsageDailyRow } from "../../shared/rpc";

const store = useMurmurStore();
const rows = ref<UsageDailyRow[]>([]);

const HEAT_DAYS = 70;

onMounted(async () => {
  try {
    rows.value = await store.usageDaily(HEAT_DAYS);
  } catch {
    // RPC 未就绪/失败时保持空态。
  }
});

const hasData = computed(() => rows.value.some((r) => r.tokens > 0));
const totalTokens = computed(() => rows.value.reduce((s, r) => s + r.tokens, 0));

/* ── 热力图：weeks × 7 rows，右端对齐今天 ── */
const dayMs = 86400_000;
const today = new Date();
today.setHours(0, 0, 0, 0);
const todayMs = today.getTime();
const mondayOffset = (today.getDay() + 6) % 7; // 周一=0
const heatStart = todayMs - mondayOffset * dayMs - (Math.ceil(HEAT_DAYS / 7) - 1) * 7 * dayMs;

const dayTotals = computed(() => {
  const m = new Map<string, number>();
  for (const r of rows.value) m.set(r.day, (m.get(r.day) ?? 0) + r.tokens);
  return m;
});

/* 色阶 ink→琥珀：用量是「agent 在叫你」的前奏，与 waiting 琥珀同族。 */
const HEAT_LEVELS = [
  "color-mix(in oklab, var(--foreground) 6%, transparent)",
  "color-mix(in oklab, var(--status-waiting) 28%, transparent)",
  "color-mix(in oklab, var(--status-waiting) 52%, transparent)",
  "color-mix(in oklab, var(--status-waiting) 78%, transparent)",
  "var(--status-waiting)",
];

interface HeatCell {
  day: string;
  tokens: number;
  color: string;
}

const heatWeeks = computed(() => {
  const max = Math.max(...dayTotals.value.values(), 1);
  const weeks: HeatCell[][] = [];
  for (let w = 0; w * 7 * dayMs + heatStart <= todayMs; w++) {
    const week: HeatCell[] = [];
    for (let d = 0; d < 7; d++) {
      const ms = heatStart + (w * 7 + d) * dayMs;
      const day = fmtDay(ms);
      const tokens = ms > todayMs ? 0 : (dayTotals.value.get(day) ?? 0);
      const lvl = tokens === 0 ? 0 : Math.min(4, Math.max(1, Math.ceil((tokens / max) * 4)));
      week.push({ day, tokens, color: HEAT_LEVELS[lvl] });
    }
    weeks.push(week);
  }
  return weeks;
});

/* ── 热力图瞬时悬浮（替代原生 title）── */
const heatBox = ref<HTMLElement | null>(null);
const heatTip = ref<ChartTipState | null>(null);
const heatCell = ref<HeatCell | null>(null);

function onHeatEnter(event: MouseEvent, cell: HeatCell) {
  if (!heatBox.value) return;
  heatCell.value = cell;
  heatTip.value = anchorTop(event, heatBox.value);
}

/* ── 近 7 天按 agent ── */
interface BarSegment {
  agent: string;
  tokens: number;
  h: number;
}

const last7 = computed(() => {
  const byAgent = new Map<string, Map<string, number>>();
  for (const r of rows.value) {
    if (!byAgent.has(r.day)) byAgent.set(r.day, new Map());
    const m = byAgent.get(r.day)!;
    m.set(r.agent, (m.get(r.agent) ?? 0) + r.tokens);
  }
  const days: { day: string; label: string; segments: BarSegment[] }[] = [];
  let maxTotal = 1;
  const totals: number[] = [];
  for (let i = 6; i >= 0; i--) {
    const ms = todayMs - i * dayMs;
    const day = fmtDay(ms);
    const m = byAgent.get(day);
    const total = m ? [...m.values()].reduce((a, b) => a + b, 0) : 0;
    totals.push(total);
    maxTotal = Math.max(maxTotal, total);
    days.push({ day, label: i === 0 ? "今天" : day.slice(5), segments: [] });
  }
  days.forEach((d, i) => {
    const m = byAgent.get(d.day);
    if (!m) return;
    const hScale = totals[i] > 0 ? Math.max(6, (totals[i] / maxTotal) * 60) : 0;
    d.segments = [...m.entries()]
      .sort((a, b) => b[1] - a[1])
      .map(([agent, tokens]) => ({ agent, tokens, h: Math.max(2, (tokens / totals[i]) * hScale) }));
  });
  return days;
});

const weekTokens = computed(() => last7.value.reduce((s, d) => s + d.segments.reduce((a, b) => a + b.tokens, 0), 0));

/* ── 堆积柱瞬时悬浮 ── */
const barBox = ref<HTMLElement | null>(null);
const barTip = ref<ChartTipState | null>(null);
const barSeg = ref<BarSegment | null>(null);

function onBarEnter(event: MouseEvent, seg: BarSegment) {
  if (!barBox.value) return;
  barSeg.value = seg;
  barTip.value = anchorTop(event, barBox.value);
}

function segName(agent: string) {
  return AGENT_META[agent as keyof typeof AGENT_META]?.name ?? agent;
}

/* ── 近 7 天按模型（top6 + 其他），数据整形后交给 ModelLineChart ── */
const MODEL_COLORS = [
  "var(--chart-1)",
  "var(--chart-2)",
  "var(--chart-3)",
  "var(--chart-4)",
  "var(--chart-5)",
  "var(--chart-6)",
  "var(--chart-7)",
];

const lineDays = computed(() => last7.value.map((d) => ({ day: d.day, label: d.label })));

const lineSeries = computed(() => {
  const dayKeys = lineDays.value.map((d) => d.day);
  const byModel = new Map<string, Map<string, number>>();
  for (const r of rows.value) {
    if (!dayKeys.includes(r.day)) continue;
    const name = (r.model ?? "unknown").split("/").pop()!;
    if (!byModel.has(name)) byModel.set(name, new Map());
    const m = byModel.get(name)!;
    m.set(r.day, (m.get(r.day) ?? 0) + r.tokens);
  }
  // top6 + 其他
  const ranked = [...byModel.entries()]
    .map(([name, m]) => ({ name, m, total: [...m.values()].reduce((a, b) => a + b, 0) }))
    .sort((a, b) => b.total - a.total);
  const top = ranked.slice(0, 6);
  const rest = ranked.slice(6);
  if (rest.length) {
    const merged = new Map<string, number>();
    for (const r of rest) for (const [d, v] of r.m) merged.set(d, (merged.get(d) ?? 0) + v);
    top.push({ name: "其他", m: merged, total: rest.reduce((s, r) => s + r.total, 0) });
  }
  return top.map((t, i) => ({
    name: t.name,
    total: t.total,
    color: MODEL_COLORS[i % MODEL_COLORS.length],
    values: dayKeys.map((d) => t.m.get(d) ?? 0),
  }));
});

const AGENT_COLORS: Record<string, string> = {
  kimi: "var(--agent-kimi)",
  zcode: "var(--agent-zcode)",
  opencode: "var(--agent-opencode)",
  codex: "var(--agent-codex)",
  cursor: "var(--agent-cursor)",
};
const agentColor = (a: string) => AGENT_COLORS[a] ?? "var(--faint)";

function fmtDay(ms: number) {
  const d = new Date(ms);
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
}

function fmt(n: number) {
  if (!n) return "0";
  if (n >= 1_000_000_000) return `${(n / 1_000_000_000).toFixed(1)}G`;
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`;
  if (n >= 1_000) return `${(n / 1_000).toFixed(1)}k`;
  return `${n}`;
}
</script>

// apps/desktop/src/mainview/components/usage-view.tsx
/**
 * 用量视图：display hero（今日令牌数字当家）→ 01 热力图（foreground 单色阶，
 * GitHub 式）→ 02 近 7 天按 agent 堆积柱 + 明细图例 → 03 近 7 天按模型折线。
 * 彩色纪律：热力图走中性色阶；agent 色只出现在「谁」语义的柱段与图例点。
 * 键盘/读屏：热力图格子与柱段 tabIndex+role=img 可聚焦，focus 与 hover 同出 ChartTip；
 * 折线的文本明细由 model-line-chart 内置 sr-only 兜底。
 * 卡片语法：三个图表区块是 flat 地面栏目（编号头 + 上 hairline），不占卡片壳——
 * 卡片只留给「可交互实体」（动态页会话组、工具页 agent 行）。
 */

import { useEffect, useMemo, useRef, useState } from "react";

import AnimatedNumber from "@/components/animated-number";
import ChartTip from "@/components/chart-tip";
import ModelLineChart from "@/components/model-line-chart";
import Murmuration from "@/components/murmuration";
import { Button } from "@/components/ui/button";
import { AGENT_META } from "@/lib/agent-meta";
import { anchorTop } from "@/lib/chart-tip";
import { fmtTokens } from "@/lib/format";
import { useMurmurStore } from "@/store/murmur";

import type { ChartTipState } from "@/lib/chart-tip";
import type { SyntheticEvent as ReactSyntheticEvent } from "react";
import type { UsageDailyRow } from "../../shared/rpc";

const HEAT_DAYS = 70;
const dayMs = 86400_000;

const today = new Date();
today.setHours(0, 0, 0, 0);
const todayMs = today.getTime();
const mondayOffset = (today.getDay() + 6) % 7; // 周一=0
const heatStart = todayMs - mondayOffset * dayMs - (Math.ceil(HEAT_DAYS / 7) - 1) * 7 * dayMs;

/* 热力图密度色阶：空档保持中性，有量后走 --heat 暖橙单色相递进——
   密度语义专属通道（既非状态也非「谁」），单色纪律不破。 */
const HEAT_LEVELS = [
  "color-mix(in oklab, var(--foreground) 6%, transparent)",
  "color-mix(in oklab, var(--heat) 22%, transparent)",
  "color-mix(in oklab, var(--heat) 45%, transparent)",
  "color-mix(in oklab, var(--heat) 70%, transparent)",
  "var(--heat)",
];

const WEEKDAY_MARKS = ["一", "", "三", "", "五", "", "日"];

const MODEL_COLORS = [
  "var(--chart-1)",
  "var(--chart-2)",
  "var(--chart-3)",
  "var(--chart-4)",
  "var(--chart-5)",
  "var(--chart-6)",
  "var(--chart-7)",
];

/* 折线系列 dash 双编码：灰阶只拉明度，细线交叉处靠线型兜底区分；
   rank0 略粗做头部层级，「其他」通常落 rank6 最虚。 */
const MODEL_LINE_STYLES: { dash?: string; width: number }[] = [
  { width: 1.75 },
  { width: 1.5 },
  { dash: "6 3", width: 1.5 },
  { dash: "2.5 2.5", width: 1.5 },
  { dash: "8 3 2.5 3", width: 1.5 },
  { dash: "1 2", width: 1.5 },
  { dash: "10 4", width: 1.5 },
];

const AGENT_COLORS: Record<string, string> = {
  kimi: "var(--agent-kimi)",
  zcode: "var(--agent-zcode)",
  opencode: "var(--agent-opencode)",
  codex: "var(--agent-codex)",
  cursor: "var(--agent-cursor)",
  devin: "var(--agent-devin)",
  qoder: "var(--agent-qoder)",
};
const agentColor = (a: string) => AGENT_COLORS[a] ?? "var(--faint)";

interface HeatCell {
  day: string;
  tokens: number;
  color: string;
}

interface BarSegment {
  agent: string;
  tokens: number;
  h: number;
}

export default function UsageView() {
  const usageDaily = useMurmurStore((s) => s.usageDaily);
  const [rows, setRows] = useState<UsageDailyRow[]>([]);
  // 三态：loading（首次拉取，骨架与图表区同高）/ error（读取失败 + 重试）/ ready（含空态）。
  const [status, setStatus] = useState<"loading" | "error" | "ready">("loading");
  const [attempt, setAttempt] = useState(0);

  useEffect(() => {
    let alive = true;
    setStatus("loading");
    usageDaily(HEAT_DAYS)
      .then((data) => {
        if (!alive) return;
        setRows(data);
        setStatus("ready");
      })
      .catch(() => {
        // RPC 未就绪/失败：显式错误态，不再让空态冒充「无数据」。
        if (alive) setStatus("error");
      });
    return () => {
      alive = false;
    };
  }, [usageDaily, attempt]);

  const hasData = rows.some((r) => r.tokens > 0);
  const totalTokens = rows.reduce((s, r) => s + r.tokens, 0);

  /* ── 热力图：weeks × 7 rows，右端对齐今天 ── */
  const dayTotals = useMemo(() => {
    const m = new Map<string, number>();
    for (const r of rows) m.set(r.day, (m.get(r.day) ?? 0) + r.tokens);
    return m;
  }, [rows]);

  const heatWeeks = useMemo(() => {
    const max = Math.max(...dayTotals.values(), 1);
    const weeks: { cells: HeatCell[]; monthLabel: string }[] = [];
    let prevMonth = -1;
    for (let w = 0; w * 7 * dayMs + heatStart <= todayMs; w++) {
      const week: HeatCell[] = [];
      for (let d = 0; d < 7; d++) {
        const ms = heatStart + (w * 7 + d) * dayMs;
        const day = fmtDay(ms);
        const tokens = ms > todayMs ? 0 : (dayTotals.get(day) ?? 0);
        const lvl = tokens === 0 ? 0 : Math.min(4, Math.max(1, Math.ceil((tokens / max) * 4)));
        week.push({ day, tokens, color: HEAT_LEVELS[lvl] });
      }
      /* 月份行：该周首日落进新月份才标，同一月内不重复 */
      const month = new Date(heatStart + w * 7 * dayMs).getMonth();
      const monthLabel = month !== prevMonth ? `${month + 1}月` : "";
      prevMonth = month;
      weeks.push({ cells: week, monthLabel });
    }
    return weeks;
  }, [dayTotals]);

  /* ── 热力图瞬时悬浮（替代原生 title）── */
  const heatBox = useRef<HTMLDivElement | null>(null);
  const [heatTip, setHeatTip] = useState<ChartTipState | null>(null);
  const [heatCell, setHeatCell] = useState<HeatCell | null>(null);

  /* 焦点事件无坐标，anchorTop 只读 currentTarget 几何——focus 与 hover 共用同一锚点逻辑。 */
  function onHeatEnter(event: ReactSyntheticEvent<HTMLElement>, cell: HeatCell) {
    if (!heatBox.current) return;
    setHeatCell(cell);
    setHeatTip(anchorTop(event, heatBox.current));
  }

  /* ── 近 7 天按 agent ── */
  const last7 = useMemo(() => {
    const byAgent = new Map<string, Map<string, number>>();
    for (const r of rows) {
      if (!byAgent.has(r.day)) byAgent.set(r.day, new Map());
      const m = byAgent.get(r.day)!;
      m.set(r.agent, (m.get(r.agent) ?? 0) + r.tokens);
    }
    const days: { day: string; label: string; segments: BarSegment[] }[] = [];
    let maxTotal = 1;
    const totals: number[] = [];
    for (let i = 6; i >= 0; i--) {
      const ms = todayMs - i * dayMs;
      const day = fmtDay(ms);
      const m = byAgent.get(day);
      const total = m ? [...m.values()].reduce((a, b) => a + b, 0) : 0;
      totals.push(total);
      maxTotal = Math.max(maxTotal, total);
      days.push({ day, label: i === 0 ? "今天" : day.slice(5), segments: [] });
    }
    days.forEach((d, i) => {
      const m = byAgent.get(d.day);
      if (!m) return;
      const hScale = totals[i] > 0 ? Math.max(6, (totals[i] / maxTotal) * 60) : 0;
      d.segments = [...m.entries()]
        .sort((a, b) => b[1] - a[1])
        .map(([agent, tokens]) => ({ agent, tokens, h: Math.max(2, (tokens / totals[i]) * hScale) }));
    });
    return days;
  }, [rows]);

  const weekTokens = last7.reduce((s, d) => s + d.segments.reduce((a, b) => a + b.tokens, 0), 0);

  /* 图例明细：近 7 天各 agent 合计与占比。 */
  const agentLegend = useMemo(() => {
    const byAgent = new Map<string, number>();
    for (const d of last7) for (const seg of d.segments) byAgent.set(seg.agent, (byAgent.get(seg.agent) ?? 0) + seg.tokens);
    return [...byAgent.entries()]
      .map(([agent, tokens]) => ({ agent, tokens, pct: weekTokens ? Math.round((tokens / weekTokens) * 100) : 0 }))
      .sort((a, b) => b.tokens - a.tokens);
  }, [last7, weekTokens]);

  /* ── 概览条：今日 / 近 7 日 / 近 10 周 / 活跃天数 ── */
  const overview = useMemo(() => {
    const todayTokens = dayTotals.get(fmtDay(todayMs)) ?? 0;
    const activeDays = [...dayTotals.values()].filter((v) => v > 0).length;
    return { todayTokens, weekTokens, totalTokens, activeDays };
  }, [dayTotals, weekTokens, totalTokens]);

  /* ── 堆积柱瞬时悬浮 ── */
  const barBox = useRef<HTMLDivElement | null>(null);
  const [barTip, setBarTip] = useState<ChartTipState | null>(null);
  const [barSeg, setBarSeg] = useState<BarSegment | null>(null);

  function onBarEnter(event: ReactSyntheticEvent<HTMLElement>, seg: BarSegment) {
    if (!barBox.current) return;
    setBarSeg(seg);
    setBarTip(anchorTop(event, barBox.current));
  }

  /* ── 近 7 天按模型（top6 + 其他），数据整形后交给 ModelLineChart ── */
  const lineDays = useMemo(() => last7.map((d) => ({ day: d.day, label: d.label })), [last7]);

  const lineSeries = useMemo(() => {
    const dayKeys = lineDays.map((d) => d.day);
    /* 模型名大小写不敏感归并（glm-5.3-flash / GLM-5.3-Flash 是同一模型）：
       key 取小写，展示名取组内累计量最大的原始变体。 */
    const byModel = new Map<string, { variants: Map<string, number>; days: Map<string, number> }>();
    for (const r of rows) {
      if (!dayKeys.includes(r.day)) continue;
      const raw = (r.model ?? "unknown").split("/").pop()!;
      const key = raw.toLowerCase();
      let g = byModel.get(key);
      if (!g) {
        g = { variants: new Map(), days: new Map() };
        byModel.set(key, g);
      }
      g.variants.set(raw, (g.variants.get(raw) ?? 0) + r.tokens);
      g.days.set(r.day, (g.days.get(r.day) ?? 0) + r.tokens);
    }
    // top6 + 其他
    const ranked = [...byModel.values()]
      .map((g) => ({
        name: [...g.variants.entries()].sort((a, b) => b[1] - a[1])[0][0],
        m: g.days,
        total: [...g.days.values()].reduce((a, b) => a + b, 0),
      }))
      .sort((a, b) => b.total - a.total);
    const top = ranked.slice(0, 6);
    const rest = ranked.slice(6);
    if (rest.length) {
      const merged = new Map<string, number>();
      for (const r of rest) for (const [d, v] of r.m) merged.set(d, (merged.get(d) ?? 0) + v);
      top.push({ name: "其他", m: merged, total: rest.reduce((s, r) => s + r.total, 0) });
    }
    return top.map((t, i) => ({
      name: t.name,
      total: t.total,
      color: MODEL_COLORS[i % MODEL_COLORS.length],
      ...MODEL_LINE_STYLES[i % MODEL_LINE_STYLES.length],
      values: dayKeys.map((d) => t.m.get(d) ?? 0),
    }));
  }, [rows, lineDays]);

  /* 入场序位：渲染顺序即 stagger 顺序 */
  let slot = 0;
  const enterDelay = () => `${slot++ * 40}ms`;

  return (
    <div className="flex flex-col gap-4">
      {status === "error" ? (
        <div className="px-4 py-14 text-center" role="alert">
          <p className="text-body font-medium">用量读取失败</p>
          <p className="mt-1.5 text-meta text-muted-foreground">本地台账暂时读不出来，稍候可重试。</p>
          <Button size="sm" className="mt-4" onClick={() => setAttempt((a) => a + 1)}>
            重试
          </Button>
        </div>
      ) : status === "loading" ? (
        <div className="space-y-3" aria-live="polite" aria-busy="true">
          {/* 骨架与图表区同高：概览 hero + 热力图 + 柱/线两段 */}
          <div className="h-16 animate-pulse rounded-item bg-raised" />
          <div className="h-40 animate-pulse rounded-item bg-raised" />
          <div className="h-28 animate-pulse rounded-item bg-raised" />
        </div>
      ) : hasData ? (
        <>
          {/* ── 概览 hero：今日令牌数字当家（display 档），右列次级尺度陪跑。
              上边线由玻璃刊头的底边线兼任，只保留下规线 ── */}
          <section
            className="animate-enter flex items-end justify-between border-b border-hairline py-3"
            style={{ animationDelay: enterDelay() }}
          >
            <div>
              <p className="eyebrow text-faint">今日令牌</p>
              <p className="mt-1 font-mono text-display font-semibold tabular-nums leading-none">
                <AnimatedNumber value={fmtTokens(overview.todayTokens)} />
              </p>
            </div>
            <div className="flex flex-col items-end gap-1 text-meta text-muted-foreground">
              <span>
                近 7 日
                <span className="ml-1.5 font-mono tabular-nums font-medium text-foreground">
                  {fmtTokens(overview.weekTokens)}
                </span>
              </span>
              <span>
                近 10 周
                <span className="ml-1.5 font-mono tabular-nums font-medium text-foreground">
                  {fmtTokens(overview.totalTokens)}
                </span>
              </span>
              <span className="font-mono text-micro tabular-nums text-faint">{overview.activeDays} 天活跃</span>
            </div>
          </section>

          {/* ── 近 10 周热力图（周为列，日为行，GitHub 式；foreground 单色阶）── */}
          <section className="animate-enter border-t border-hairline pt-3" style={{ animationDelay: enterDelay() }}>
            <div className="mb-2 flex items-baseline justify-between">
              <span className="flex items-baseline gap-1.5">
                <span className="font-mono text-micro text-faint">01</span>
                <span className="text-detail font-semibold">近 10 周</span>
              </span>
              <span className="flex items-center gap-1 font-mono text-micro text-faint">
                少
                {HEAT_LEVELS.map((c) => (
                  <span key={c} className="h-[7px] w-[7px] rounded-[2px]" style={{ background: c }} />
                ))}
                多
              </span>
            </div>
            <div ref={heatBox} className="relative">
              {/* 月份行：与周列对齐（左缩进 = 星期列宽 + 列距） */}
              <div className="mb-1 flex gap-[3px] pl-[15px]">
                {heatWeeks.map((week, wi) => (
                  <span key={wi} className="flex-1 truncate font-mono text-micro leading-none text-faint">
                    {week.monthLabel}
                  </span>
                ))}
              </div>
              <div className="flex gap-[3px]">
                {/* 星期列：一三五日标在隔行，GitHub 惯例 */}
                <div className="flex w-3 shrink-0 flex-col gap-[3px]">
                  {WEEKDAY_MARKS.map((mark, i) => (
                    <span
                      key={i}
                      className="flex h-[11px] items-center justify-center font-mono text-micro leading-none text-faint"
                    >
                      {mark}
                    </span>
                  ))}
                </div>
                {heatWeeks.map((week, wi) => (
                  <div key={wi} className="flex flex-1 flex-col gap-[3px]">
                    {week.cells.map((cell) => (
                      <span
                        key={cell.day}
                        role="img"
                        aria-label={`${cell.day} ${fmtTokens(cell.tokens)} 令牌`}
                        tabIndex={0}
                        className="h-[11px] w-full rounded-[2.5px] transition-shadow duration-fast hover:ring-1 hover:ring-foreground/25 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-foreground/40"
                        style={{ background: cell.color }}
                        onMouseEnter={(e) => onHeatEnter(e, cell)}
                        onMouseLeave={() => setHeatTip(null)}
                        onFocus={(e) => onHeatEnter(e, cell)}
                        onBlur={() => setHeatTip(null)}
                      />
                    ))}
                  </div>
                ))}
              </div>
              <ChartTip tip={heatTip}>
                {heatCell && (
                  <p className="whitespace-nowrap text-meta">
                    <span className="font-mono tabular-nums text-faint">{heatCell.day}</span>
                    <span className="mx-1.5 text-faint">·</span>
                    <span className="font-mono tabular-nums font-medium">{fmtTokens(heatCell.tokens)} 令牌</span>
                  </p>
                )}
              </ChartTip>
            </div>
          </section>

          {/* ── 近 7 天堆积柱（按 agent 分色）+ 明细图例 ── */}
          <section className="animate-enter border-t border-hairline pt-3" style={{ animationDelay: enterDelay() }}>
            <div className="mb-2 flex items-baseline justify-between">
              <span className="flex items-baseline gap-1.5">
                <span className="font-mono text-micro text-faint">02</span>
                <span className="text-detail font-semibold">近 7 天 · 按工具</span>
              </span>
              <span className="font-mono text-micro tabular-nums text-faint">{fmtTokens(weekTokens)} 令牌</span>
            </div>
            <div ref={barBox} className="relative">
              <div className="flex h-[84px] items-end gap-2">
                {last7.map((d) => (
                  <div key={d.day} className="flex flex-1 flex-col items-center gap-1">
                    <div className="flex w-full flex-col-reverse gap-px" style={{ height: "64px" }}>
                      {d.segments.map((seg) => (
                        <div
                          key={seg.agent}
                          role="img"
                          aria-label={`${segName(seg.agent)} ${fmtTokens(seg.tokens)} 令牌`}
                          tabIndex={0}
                          className="w-full rounded-[2px] transition-opacity duration-fast hover:opacity-80 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-foreground/40"
                          style={{ height: `${seg.h}px`, background: agentColor(seg.agent) }}
                          onMouseEnter={(e) => onBarEnter(e, seg)}
                          onMouseLeave={() => setBarTip(null)}
                          onFocus={(e) => onBarEnter(e, seg)}
                          onBlur={() => setBarTip(null)}
                        />
                      ))}
                    </div>
                    <span className="font-mono text-micro tabular-nums text-faint">{d.label}</span>
                  </div>
                ))}
              </div>
              <ChartTip tip={barTip}>
                {barSeg && (
                  <p className="whitespace-nowrap text-meta">
                    <span className="font-medium">{segName(barSeg.agent)}</span>
                    <span className="mx-1.5 text-faint">·</span>
                    <span className="font-mono tabular-nums">{fmtTokens(barSeg.tokens)} 令牌</span>
                  </p>
                )}
              </ChartTip>
            </div>
            <div className="mt-2 flex flex-col gap-1 border-t border-hairline/60 pt-2">
              {agentLegend.map((a) => (
                <span key={a.agent} className="flex items-center gap-1.5 text-meta">
                  <span
                    className="h-[6px] w-[6px] shrink-0 rounded-full"
                    style={{ background: agentColor(a.agent) }}
                  />
                  <span className="text-muted-foreground">{segName(a.agent)}</span>
                  <span className="ml-auto font-mono tabular-nums text-faint">{a.pct}%</span>
                  <span className="w-9 text-right font-mono tabular-nums">{fmtTokens(a.tokens)}</span>
                </span>
              ))}
            </div>
          </section>

          {/* ── 近 7 天模型折线（准星 + 悬浮明细 + 峰值标注）── */}
          <section className="animate-enter border-t border-hairline pt-3" style={{ animationDelay: enterDelay() }}>
            <div className="mb-2 flex items-baseline gap-1.5">
              <span className="font-mono text-micro text-faint">03</span>
              <span className="text-detail font-semibold">近 7 天 · 按模型</span>
            </div>
            <ModelLineChart days={lineDays} series={lineSeries} />
            <div className="mt-1.5 flex flex-wrap gap-x-3 gap-y-1">
              {lineSeries.map((m) => (
                <span key={m.name} className="flex items-center gap-1 text-micro text-muted-foreground">
                  {/* 线样图例：dash 双编码在图例里同样可读，圆点表达不了线型 */}
                  <svg width="14" height="4" className="shrink-0" aria-hidden="true">
                    <line
                      x1="1"
                      y1="2"
                      x2="13"
                      y2="2"
                      stroke={m.color}
                      strokeWidth={m.width}
                      strokeDasharray={m.dash}
                      strokeLinecap="round"
                    />
                  </svg>
                  {m.name}
                  <span className="font-mono tabular-nums text-faint">{fmtTokens(m.total)}</span>
                </span>
              ))}
            </div>
          </section>
        </>
      ) : (
        <div className="animate-enter px-3 py-14 text-center" style={{ animationDelay: enterDelay() }}>
          <Murmuration size={120} className="mx-auto" />
          <p className="mt-4 text-body font-medium">还没有用量记录</p>
          <p className="mt-1.5 text-meta leading-relaxed text-muted-foreground">
            agent 跑起来后，这里会出现热力图与模型用量曲线
          </p>
        </div>
      )}
    </div>
  );
}

function segName(agent: string) {
  return AGENT_META[agent as keyof typeof AGENT_META]?.name ?? agent;
}

function fmtDay(ms: number) {
  const d = new Date(ms);
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
}
